### ISSUE TITLE
Size of arrows on Links is wrong when zooming then switching to draw->text->draw view

### ISSUE THREAD

**Issue by viennem** [ditrit/leto-modelizer-plugin-core#212]
**Describe the bug**

The size of arrows on Links is wrong when zooming then switching to draw view, then text view, then back to draw view.

**To Reproduce**

https://github.com/ditrit/leto-modelizer-plugin-core/assets/20184007/8c6ab580-a59a-4f7b-b109-94496e6f6109

**Application**

- `leto-modelizer` commit hash: `f59e63e9d861fb5d0f0849dc7983be3a76bd779a`.
- `leto-modelizer-plugin-core` version: `#0.19.0`.
- `terrator-plugin` version: `#0.5.0`.

**Comment by justinehell** [comment]
Bug fixed by this PR https://github.com/ditrit/leto-modelizer/pull/398
